Repository MINI-TEAM3/admin, pull requests merged in 2023-08, with the labels that each got.

#2 ✨ Feat: 라우터 설정, 전역 스타일 추가, Recoil 설치
  index.html
  package-lock.json
  package.json
  src/components/MainHeader.tsx
  src/components/SideBar.tsx
  src/pages/Annual.tsx
  src/pages/Duty.tsx
  src/pages/Layout.tsx
  src/pages/Login.tsx
  src/pages/index.tsx
  src/styles/GlobalStyle.ts
  vite.config.ts
Labels: 문서 수정, 새로운 기능

#5 :sparkles: Feat: 사이드바 레이아웃 구성, 기능 구현
  src/components/SideBar.tsx
  src/styles/Themes.ts
Labels: 새로운 기능

#9 :sparkles: Feat: 기본 버튼, 승인/반려 버튼 추가
  src/components/Buttons/ApplyBtn.tsx
  src/components/Buttons/Btn.tsx
  src/components/Buttons/RejectBtn.tsx
Labels: 새로운 기능

#12 ✨ Feat: Recoil 설치, RecoilRoot, 로그인 페이지 코드 최신화
  package-lock.json
  package.json
  src/App.tsx
  src/lib/Validation/validation.ts
  src/lib/api/index.ts
  src/lib/types/index.ts
  src/pages/Login.tsx
  src/states/stateLogin.ts
Labels: 새로운 기능

#14 :sparkles: Feat: 어드민 페이지 로그인 기능 연결, API 모듈 return 값 변경
  src/lib/Validation/validation.ts
  src/lib/api/index.ts
  src/pages/Login.tsx
Labels: 새로운 기능

#17 ✨ Feat: 메인 헤더 관리자 재직 병원명 출력
  src/components/MainHeader.tsx
  src/lib/api/index.ts
  src/pages/Login.tsx
Labels: 새로운 기능

#20 ✨ Feat: 어드민 당직 변경 관리 API 연결 및 기능 구현
  src/components/Buttons/ApplyBtn.tsx
  src/components/Buttons/RejectBtn.tsx
  src/components/duty/DutyRequestsItem.tsx
  src/lib/types/index.ts
  src/pages/Duty.tsx
Labels: 새로운 기능

#23 :lipstick: Design: 전역 디자인 추가, 파비콘 수정
  index.html
  public/arrow.png
  public/favicon.png
  public/vite.svg
  src/pages/Requests.tsx
  src/styles/GlobalStyle.ts
Labels: 문서 수정

#26 ✨ Feat: 당직 변경 관리 페이지 정렬 및 버튼 클릭 이벤트 추가, 미사용 코드 삭제
  src/components/Buttons/ApplyBtn.tsx
  src/components/Buttons/RejectBtn.tsx
  src/components/duty/DutyRequestsItem.tsx
  src/pages/Duty.tsx
Labels: 새로운 기능

#36 :sparkles: Feat: 로딩 스피너 추가
  src/components/Loading.tsx
  src/pages/Duty.tsx
Labels: 새로운 기능

#41 :bug: Fix: 캘린더 당직 수정 오류 체크, 콘솔 로그 삭제
  src/components/calendar/CalendarBody.tsx
  src/components/requests/RequestsItem.tsx
  src/lib/api/index.ts
Labels: 버그

#43 :rotating_light: HOTFIX: API HOST 적용
  src/lib/api/index.ts
Labels: 버그
